import type { Metadata } from "next";
import headerStyles from "./Header.module.css";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meu Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-br"
      className={` h-full `}
    >
      <body className="min-h-full flex flex-col">
        <header className={headerStyles.header}>
          <Link className={headerStyles.header_titulo} href="/">Blog</Link>
        </header>
    
        {children}
      
      </body>
    </html>
  );
}
